[package]
name = "league-a-lot"
version = "0.1.0"
authors = ["Zach Schuermann <zachary.zvs@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.11"
env_logger = "0.8.2"
surf = "2.1.0"
chrono = "0.4"

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]
